nelmio_cors:
        defaults:
            allow_origin:  ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            allow_headers: ["Origin","Accept","content-type", "Authorization","X-Auth-Token"]
            max_age: 3600
        paths:
            '^/api/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ["Origin","Accept","content-type", "Authorization","X-Auth-Token"]
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/login/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ["Origin","Accept","content-type", "Authorization","X-Auth-Token"]
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ["Origin","Accept","content-type", "Authorization","X-Auth-Token"]
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']